Description of createNetz
createNetz
PURPOSE
dimension
SYNOPSIS
function Netz = createNetz()
DESCRIPTION
dimension
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
graph
graph_distribution precondition
runsim % simulation parameter
runsim_distribution postcondition
runsimold % simulation parameter
SOURCE CODE
function Netz = createNetz()
    %dimension
    n=42;
    Netz=cell(n);
    Netz(1,7)={17};
    Netz(2,7)={4};
    Netz(3,6)={2};
    Netz(4,6)={3};
    Netz(5,8)={9};
    Netz(6,8)={[2,3]};
    Netz(7,14)={[4,17]};
    Netz(8,13)={[2,9]};
    Netz(8,15)={[3,8]};
    Netz(9,11)={[5,13]};
    Netz(10,11)={7};
    Netz(11,42)={5};
    Netz(11,13)={[6,7,13]};
    Netz(12,42)={[2,5,8,9,11]};
    Netz(12,28)={[2,4]};
    Netz(12,25)={[11,15]};
    Netz(12,30)={[5,8,9]};
    Netz(12,17)={[4,15]};
    Netz(13,42)={[2,8,9,11]};
    Netz(13,16)={[6,7,11,13]};
    Netz(14,15)={[14,17]};
    Netz(14,31)={[11,14]};
    Netz(14,16)={[11,13]};
    Netz(14,17)={4};
    Netz(15,17)={[3,10]};
    Netz(16,17)={[6,7]};
    Netz(17,18)={[6,7,10,15]};
    Netz(17,30)={3};
    Netz(18,19)={[6,10]};
    Netz(18,31)={[7,15]};
    Netz(19,20)={9};
    Netz(19,21)={6};
    Netz(19,32)={[9,10]};
    Netz(20,21)={5};
    Netz(20,30)={[5,9]};
    Netz(21,22)={[5,6]};
    Netz(22,23)={6};
    Netz(24,25)={15};
    Netz(24,26)={[3,8,15]};
    Netz(24,30)={[3,8]};
    Netz(25,27)={11};
    Netz(27,29)={11};
    Netz(31,32)={[7,14]};
    Netz(31,33)={[11,15]};
    Netz(32,34)={[7,9]};
    Netz(32,37)={[10,14]};
    Netz(33,37)={11};
    Netz(34,35)={7};
    Netz(34,36)={9};
    Netz(37,38)={[10,14]};
    Netz(37,39)={11};
    Netz(38,40)={14};
    Netz(38,41)={10};
    %make the matrix symmetric
    for i=1:n
       for j=1:n
           [sn, sm] = size(Netz{i,j});
           if sn==0&&sm==0
               Netz(i,j)={0};
           end
           Netz(j,i)=Netz(i,j);
       end
    end
end