Description of getstats
getstats
PURPOSE
calculate percentages
SYNOPSIS
function [counts,percentage] = getstats(Statistic)
DESCRIPTION
 calculate percentages
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
runsim % simulation parameter
runsim_distribution postcondition
runsimold % simulation parameter
SOURCE CODE
function [counts,percentage] = getstats(Statistic)
% calculate percentages
%
controldoging = sum(Statistic(:,2));
controlnondoging = sum(Statistic(:,3));
totalcontrols = controlnondoging+controldoging;
totaldoging = sum(Statistic(:,1));
totaltours = sum(Statistic(:,4));
format shortg
percentage=[totalcontrols/totaltours,totaldoging/totaltours,controldoging/totalcontrols];
counts=[controldoging,controlnondoging,totalcontrols, totaldoging, totaltours-totaldoging, totaltours];